### ISSUE TITLE
Pass default phone country as option?

### ISSUE THREAD

**Issue by farwayer** [Salesflare/joi-phone-number#12]
It is US now

**Comment by AdriVanHoudt** [comment]
As in `Joi.string().phoneNumber('BE')` or at extend time like `const myCustomJoi = Joi.extend(require('joi-phone-number')('BE'));`

**Comment by farwayer** [comment]
Change is very simple:
```js
rules: [{
...
  params: {
    defaultCountry: joi.string().default('US'),
  },
  validate(params, value, state, options) {
    PhoneUtil.parse(value, params.defaultCountry);
...
```

**Comment by AdriVanHoudt** [comment]
That would result in `Joi.string().phoneNumber('BE')` if I'm correct?
I like it, you basically already wrote the patch so if you want I will take a PR for it!
(you can even get a tshirt for it ;) https://hacktoberfest.digitalocean.com/ )
