### ISSUE TITLE
PR for getNumberType and error.messages

### ISSUE THREAD

**Issue by basaran** [Salesflare/joi-phone-number#181]
Hello,

Thank you for the extension. Can I send a PR to add another parameter to the rule object { mobile: boolean } ?

**Comment by AdriVanHoudt** [comment]
Hi @basaran 

PRs are always welcome, what would the mobile param do?

**Comment by basaran** [comment]
Hi, apparently there are PhoneNumberType enums with the library. It tells you if the phonenumber is fixed, mobile or fixed_line_or_mobile. It's not very accurate for US, Canada numbers (mostly returns fixed_line_or_mobile) but for some countries, it appears to spot on.

**Comment by AdriVanHoudt** [comment]
Feel free to submit a PR, note that this rule gives back a string atm so I wouldn't know how to achieve what you want top of my head. But I'm interested in your PR for sure.

**Comment by basaran** [comment]
PR sent, please let me know if there are any issues.
