### ISSUE TITLE
I can add char after the phone number

### ISSUE THREAD

**Issue by sarovin** [Salesflare/joi-phone-number#21]
My function
```
import Joi from 'joi';
import JoiPhoneNumber from 'joi-phone-number';

export default (value) => Joi.extend(JoiPhoneNumber).string().phoneNumber({ defaultCountry: 'IT', format: 'international' }).validate(value)
```

Value = `00393926655111fgv`
Result = `+39 3926655111348`

Why can i add a char after phone number?

**Comment by AdriVanHoudt** [comment]
For questions about the parsing see the Google lib.
I think your question is answered here https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-does-the-library-treat-some-non-digit-characters-as-digits
