### ISSUE TITLE
check israeli valid phone number

### ISSUE THREAD

**Issue by adirzoari** [Salesflare/joi-phone-number#27]
Hello,
I would like to know how can I check valid israeli phone number?
valid phones:
```
+972 052 xxxxxxx
+972 054 xxxxxxx
+972 050 xxxxxxx
+972 053 xxxxxxx

```

**Comment by AdriVanHoudt** [comment]
The validation is done with https://github.com/googlei18n/libphonenumber and they have a demo here https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
If that can't do what you want open an issue there
If you are specifically asking how to use this module let me know

**Comment by adirzoari** [comment]
it works in javascript also?
I see it java code.

**Comment by AdriVanHoudt** [comment]
the js is here https://github.com/googlei18n/libphonenumber/tree/master/javascript/i18n/phonenumbers
This module uses https://github.com/ruimarinho/google-libphonenumber which is the same source compiled differently for easier use in node

**Comment by adirzoari** [comment]
great thanks.

**Comment by AdriVanHoudt** [comment]
Is that the info you were looking for? If so you can close this issue :D

**Comment by adirzoari** [comment]
yes I think so. if it works with Joi, so that fine.

**Comment by AdriVanHoudt** [comment]
that's the purpose of this module ^^
