### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [Salesflare/joi-phone-number#46]
I just saw the package is updated to `v2.0.15`, but I can't find any CHANGELOG to check out the changes.

Would you guys be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work! 🙂

**Comment by AdriVanHoudt** [comment]
Hey Michael, 

Considering 90% of the updates on this package will be bumping the the libphonenumber dependency I think it is easier to look at the commit list then to look at an actual changelog https://github.com/Salesflare/joi-phone-number/commits/master
If you want to know what changed in that lib then I can point you to https://github.com/googlei18n/libphonenumber/blob/master/release_notes.txt
If you want I can add this information to the readme.

**Comment by AdriVanHoudt** [comment]
Done 👌 

Are you using just Joi or also hapi? Always cool to know how/what people are building/using :D

**Comment by MichaelDeBoey** [comment]
@AdriVanHoudt We're only using `joi` in our project

**Comment by AdriVanHoudt** [comment]
Cool to see other Belgians use Joi 😎
