### ISSUE TITLE
Joi.Ref as country

### ISSUE THREAD

**Issue by sm2017** [Salesflare/joi-phone-number#50]
It's good to support Joi.Ref in options

```js
myCustomJoi.string().phoneNumber({ defaultCountry:Joi.Ref('country'), format: 'e164' }).validate('494322456'); // '+32494322456'
```

**Comment by AdriVanHoudt** [comment]
@sm2017 that would be great, I don't know from the top of my head how to do this though.
If you do, PR is welcome!

**Comment by sm2017** [comment]
See https://github.com/hapijs/joi/blob/master/lib/types/number/index.js#L213 and https://github.com/hapijs/joi/blob/master/lib/types/number/index.js#L222

You can use `isRef` and `parameter(state.reference || state.parent, options);`

**Comment by AdriVanHoudt** [comment]
Cool, I'll see when I can do this. Otherwise you can do a PR and I will gladly help merge it ✨
