### ISSUE TITLE
Phone number in schema

### ISSUE THREAD

**Issue by oreshkoandrei** [Salesflare/joi-phone-number#55]
Hello

Is there a way to use it in joi schemas ?

**Comment by AdriVanHoudt** [comment]
Hi @oreshkoandrei 
It is in the readme https://github.com/Salesflare/joi-phone-number#how
Is there anything not clear about it?

**Comment by oreshkoandrei** [comment]
> Hi @oreshkoandrei
> It is in the readme https://github.com/Salesflare/joi-phone-number#how
> Is there anything not clear about it?

hm, but it require to pass phone in validate(), actually. Any way to avoid this ?

**Comment by AdriVanHoudt** [comment]
I don't understand your question. Do you have an example of what you are trying to do and what it not working or what you expect it to do?
This rule adds `.phoneNumber()` onto `.string()` so you have to do `Joi.string().phoneNumber()` not `Joi.phoneNumber()`

**Comment by oreshkoandrei** [comment]
Okey, i'm trying to do it simply as

export default Joi.object().keys({
    id: Joi.number().greater(0),
    firstName: Joi.string().required(),
    lastName: Joi.string().required(),
    email: Joi.string().email().required(),
    **phoneNumber: myCustomJoi.string().phoneNumber()**
});

**Comment by AdriVanHoudt** [comment]
I see, you need to use your custom Joi everywhere.
For example what we did was create a scoped joi package `@salesflare/joi` that we require everywhere instead of Joi itself. The whole api stays the same but we get the extensions easily (see https://github.com/Salesflare/joi/blob/master/lib/index.js)

You should do 
```js
export default myCustomJoi.object().keys({
    id: myCustomJoi.number().greater(0),
    firstName: myCustomJoi.string().required(),
    lastName: myCustomJoi().required(),
    email: myCustomJoi.string().email().required(),
    phoneNumber: myCustomJoi.string().phoneNumber() // <--
});
```
The more detailed explanation is, is that hapi calls validate for you when doing payload validation. So it calls .validate onto that schema. In your case that schema is made with vanilla joi causing it to validate with vanilla joi. Which doesn't know what that phonenumber rule thing is. If you make your schema with your custom joi it will know about the custom rule and it should work I believe.

**Comment by oreshkoandrei** [comment]
Looks like, it now works in some way, thanks you very much
Bu i can't get why are two digits is a valid phone number )

**Comment by AdriVanHoudt** [comment]
Take a look at https://github.com/google/libphonenumber (which is what this module uses), there are some interesting links there as well. Phone numbers can be weird :D

**Comment by oreshkoandrei** [comment]
> https://github.com/google/libphonenumber

Thanks

**Comment by oreshkoandrei** [comment]
> Take a look at https://github.com/google/libphonenumber (which is what this module uses), there are some interesting links there as well. Phone numbers can be weird :D

Thanks

**Comment by AdriVanHoudt** [comment]
No problem!

**Comment by rickysullivan** [comment]
I also can't work out why **112** is valid when passing `NZ` as *defaultCountry*

```
import HapiJoi from "@hapi/joi";
const Joi = HapiJoi.extend(require("joi-phone-number"));

const validationSchema = Joi.object().keys({
  phone: Joi.string()
    .phoneNumber({ defaultCountry: "NZ", format: "national" })
    .required()
});

```
http://libphonenumber.appspot.com/phonenumberparser?number=112&country=NZ&geocodingLocale=en-NZ

**Comment by MarianMichalovic** [comment]
> I also can't work out why **112** is valid when passing `NZ` as _defaultCountry_
> 
> ```
> import HapiJoi from "@hapi/joi";
> const Joi = HapiJoi.extend(require("joi-phone-number"));
> 
> const validationSchema = Joi.object().keys({
>   phone: Joi.string()
>     .phoneNumber({ defaultCountry: "NZ", format: "national" })
>     .required()
> });
> ```
> 
> http://libphonenumber.appspot.com/phonenumberparser?number=112&country=NZ&geocodingLocale=en-NZ

Try { defaultCountry: "NZ", format: "national", strict: true }
