### ISSUE TITLE
Feature Request: Typings

### ISSUE THREAD

**Issue by CatGuardian** [Salesflare/joi-phone-number#56]
Hello,

I have a feature request. It would be nice to create a '@types/joi-phone-number' typings entry for developers using TypeScript.

Right now this is what I'm doing:

```
import * as baseJoi from 'joi';
import * as joiPhoneNumber from 'joi-phone-number';

const joi: baseJoi.Root = baseJoi.extend(joiPhoneNumber);

...
const schema = joi.object({
   phone: joi.string().phoneNumber(), // Error is here
});
```

But I get an error because `phoneNumber()` isn't a recognized property of the type that `joi.string()` returns.

So when creating a typings entry for the joi-phone-number perhaps you could export a type that adds the `phoneNumber()` to the `baseJoi.Root` typing. Then instead of 
```
const joi: baseJoi.Root = baseJoi.extend(joiPhoneNumber);
```
I can do this:

```
const joi: joiPhoneNumber.Root = baseJoi.extend(joiPhoneNumber);
```

Just a thought.

**Comment by CatGuardian** [comment]
Thinking about it a little more, I found some more info from a closed issue of the main joi typings section: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30877

Here is their code example on how to properly type the resulting object that results from adding an extension:

```
export declare type JoiType = typeof joi;
export interface ExtendedStringSchema extends joi.StringSchema {
    filename(): this;
    password(minScore: number): this;
}
export interface ExtendedArraySchema extends joi.ArraySchema {
    delim(delimeter: string): this;
}
export interface ExtendedSchema extends JoiType {
    date(): ExtendedDateSchema;
    string(): ExtendedStringSchema;
    array(): ExtendedArraySchema;
}
const mySchema = <ExtendedSchema>joi.extend(...)
```

So you would actually make an entry:

```
export interface ExtendedStringSchema extends joi.StringSchema {
    phoneNumber(...): <proper return type>, // Fill out the details of the phoneNumber method including the proper return type.
}
```

Then if the consumer of the joi-phone-number also uses multiple extensions then it would be there responsibility to do this part:

```
export declare type JoiType = typeof joi;

export interface ExtendedSchema extends JoiType {
    string(): joiPhoneNumber.ExtendedStringSchema & otherExtension.ExtendedStringSchema;
}

const mySchema = <ExtendedSchema>joi.extend(...)
```

**Comment by CatGuardian** [comment]
I actually decided to type it up in my own typescript file so I got you well on your way to adding the typings.

Here is the basic outline, there is a little bit of work to do (see the TODOs) and you would want to review it line by line yourself to make sure we are not missing anything.

```
import * as baseJoi from 'joi';
import * as joiPhoneNumber from 'joi-phone-number';


interface JoiPhoneNumberOptions {
  defaultCountry: string; // TODO: specify the actual possible countries, ie: 'BE' | 'USA' | ...
  format: string; // TODO: specify the actual possible format strings, ie: 'e164' | 'international' | ...
}

interface ExtendedJoiStringSchema extends baseJoi.StringSchema {
  phoneNumber(options?: JoiPhoneNumberOptions): this;
}

interface ExtendedJoi extends baseJoi.Root {
  string(): ExtendedJoiStringSchema;
}

const joi: ExtendedJoi = baseJoi.extend(joiPhoneNumber);
```

**Comment by AdriVanHoudt** [comment]
Hi @CatGuardian 

Props for the effort you put into this issue ✨
As we don't use typescript and I also don't have experience with it I don't think adding the types to the repo will be handy.
I suggest either doing a PR to https://github.com/DefinitelyTyped/DefinitelyTyped
or I will also gladly take a PR to add typings via jsdoc.
The only thing is that when you start to add more joi extensions the type building will be your own responsibility I think.

**Comment by CatGuardian** [comment]
Yeah the way they have it implemented now it looks like the developer has to build the final Joi typings that include all of the extensions typings. But the extension could maybe publish helper types that could be concatenated together by the developer.

I honestly probably won't put out typings for this library at this point by going through the definitely typed process just because I don't have free time at the moment. So maybe another community member can stumble upon this and feel empowered.

**Comment by AdriVanHoudt** [comment]
I don't know the definitelytyped process :/
If someone has pointers to what I can do in jsdoc to help then I will gladly modify that!
