### ISSUE TITLE
Bug: Doesn't Use The Phone Utility's isValidNumber() Method

### ISSUE THREAD

**Issue by CatGuardian** [Salesflare/joi-phone-number#57]
The Google Library has a method for checking to see if the phone number is valid:

```
const phoneUtil = require('google-libphonenumber').PhoneNumberUtil.getInstance();

// Parse number with country code and keep raw input.
const number = phoneUtil.parseAndKeepRawInput('202-456-1414', 'US');

// Result from isValidNumber().
console.log(phoneUtil.isValidNumber(number));
// => true
```

And according to the documentation: `isValidNumber(number) - tests whether a phone number matches a valid pattern.`  (https://github.com/ruimarinho/google-libphonenumber)

The issue is that I don't think the joi-phone-number uses that method to check to see if the phone is valid or not.

I enter in `7777777777` and the joi-phone-number code doesn't flag that as an error. But I type that number into the google utils demo app and it reports that the `isValidNumber(...)` method returns false for the `7777777777` number. See here: http://libphonenumber.appspot.com/phonenumberparser?number=7777777777&country=US

The same thing is true for '1234567890': the joi-phone-number doesn't flag that as an error but the `isValidNumber(...)` method returns false.

So I think there is a bug here.

Here is my joi schema statement:

```
...

// I want the phone number to be a valid phone number according to the Google Phone library
// I want the phone number to still be in the ########## format
// I want the phone number to be allowed to be null and when it is null then default to a specific phone number
// I don't want to convert to the 'e164' format so I use the .raw() to keep the original 10 digit value
// And when the phone number isn't specified at all or is null then I want it to default to a specific phone number.

phone: joi.string().empty(null).regex(/^\d{10}$/).phoneNumber({ defaultCountry: 'US', format: 'e164' }).raw().default('5152987228'),

...
```

**Comment by AdriVanHoudt** [comment]
Hmm 
What I got from the source code was that parse did more extensive testing on whether the number is valid https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumberutil.js#L4125
Sadly their js demo is down so I can't immediately test it.
I would recommend to post this question on the google repo to ask what the right approach is since I don't know now :D

**Comment by CatGuardian** [comment]
I'm not exactly sure I followed what you were saying but I think I got the jist.

I would say though that you still do what you are doing now via the parse method, but then additonally after the parse method returns the object, you also call the `isValidNumber()` just to make sure.

That is what we do in our code somewhere that wasn't joi related:

```
import { PhoneNumberFormat, PhoneNumberUtil } from 'google-libphonenumber';

const phoneUtil = PhoneNumberUtil.getInstance();

const recipient = phoneUtil.parse(faxDetails.to.fax, 'US');
CHCError.assert(phoneUtil.isValidNumber(recipient), 'Invalid recipient fax number.', 400); // CHCError.assert will throw an error if the expression is false
const recipientE164 = phoneUtil.format(recipient, PhoneNumberFormat.E164);
```

**Comment by AdriVanHoudt** [comment]
You are saying joi-phone-number is to lax now right?
And that if .parse works that doesn't necessarily mean that .isValidNumber returns true? I expected this to be the case I guess.
I would have to check on current numbers whether this would flag them as invalid.
In the meantime if you would need this strictness I would take a PR that add the isValidNumber check optionally.

**Comment by CatGuardian** [comment]
Yeah I am thinking joi-phone-number is too lax right now.
Right now .parse allows `7777777777` but calling a subsequent .isValidNumber on the entity that .parse returns for the `7777777777` will return false.

Hopefully it is as simple as adding the extra check to the code and all tests continue to pass as normal and that only adding a couple more tests like the one above will suffice.

Looking forward to the update.

Thank you for working with me on this. I do appreciate it. :)
