### ISSUE TITLE
Missing knownErrors managed

### ISSUE THREAD

**Issue by jrpedrianes** [Salesflare/joi-phone-number#74]
Appears that you have missing handle some google-libphonenumber errors. The library throw the next errors:

```
i18n.phonenumbers.Error = {INVALID_COUNTRY_CODE:"Invalid country calling code", NOT_A_NUMBER:"The string supplied did not seem to be a phone number", TOO_SHORT_AFTER_IDD:"Phone number too short after IDD", TOO_SHORT_NSN:"The string supplied is too short to be a phone number", TOO_LONG:"The string supplied is too long to be a phone number"};
```

Is this intentionally?

**Comment by AdriVanHoudt** [comment]
Not intentional. I've never seen the other ones pop up ^^
If you want you can add some tests that trigger the missing errors. Handling them shoudn't be to hard https://github.com/Salesflare/joi-phone-number/blob/master/lib/index.js#L56

**Comment by jrpedrianes** [comment]
@AdriVanHoudt is this ok for you?

**Comment by AdriVanHoudt** [comment]
Hey @jrpedrianes I'm kinda busy atm but I will get to this soon.
Is this blocking you?

**Comment by jrpedrianes** [comment]
No no, thanks, I have a little workaround implemented.

**Comment by AdriVanHoudt** [comment]
Thanks for the PR
