### ISSUE TITLE
Types for TS?

### ISSUE THREAD

**Issue by taranvohra** [Salesflare/joi-phone-number#78]
Possible to get typescript support?

**Comment by AdriVanHoudt** [comment]
What kind of typing support are you looking for? For the module itself or for when you do `joi.string().phoneNumber()` or something else?

**Comment by taranvohra** [comment]
Well yes. Right now I cannot even extend the schema because typescript yells at me.

**Comment by AdriVanHoudt** [comment]
We don't use typescript so converting the whole thing would make it difficult to maintain.
Is it possible to solve your issue by updating/adding/refining the jsdoc?

**Comment by taranvohra** [comment]
@AdriVanHoudt sorry for late response. I don't think I can spare alot of time right now doing that. I'll see what else I can do in the meanwhile

**Comment by AdriVanHoudt** [comment]
Yeah we don't use TS so it would be hard for me to fix the issue.
If you have a solution that could work or a PR I'm happy to take a look at it.

**Comment by soullivaneuh** [comment]
@AdriVanHoudt As far as I know, provide TS typing on your code definition is the only thing to provide typing and autocompletion support. Something like this: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/abbrev/index.d.ts

Am I right?

**Comment by AdriVanHoudt** [comment]
VSCode (through ts) definitely uses jsdoc for typing as well.
If someone wants to make a definitely typed thing I'm happy to take a look at it. No guarantees since we don't use ts internally though.

**Comment by NurMarvin** [comment]
Hey :wave:,
I know this issue is pretty old but I just created typings for this package, in case anyone needs them in the future, and PR'd them to the DefinitelyTyped repository here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49379
Once that PR is merged, it should be possible to get the typings via the `@types/joi-phone-number` NPM package 😃

**Comment by AdriVanHoudt** [comment]
@NurMarvin very cool! Thanks for doing this ✨
