### ISSUE TITLE
Node engine incompatibilty

### ISSUE THREAD

**Issue by saratonite** [Salesflare/joi-phone-number#92]
The engine "node" is incompatible with this module. Expected version ">=12.16.0". Got "10.16.0"

my node version : 10.16.*

currently, I cant upgrade node version on my production machine!

**Comment by AdriVanHoudt** [comment]
Hi @saratonite 
We use node 12 as the minimum node version so all our packages aim to set that restriction.
I think this lib should work on node 10 if you really want to use it and the reason you get that error is because npm is strictly checking the engines field (there is an option for it)

**Comment by saratonite** [comment]
Okay got it
